// Code generated by lungo-dist; DO NOT EDIT.

//go:build windows && amd64

package lungo

// #cgo LDFLAGS: ${SRCDIR}/lib/windows_amd64/liblungo.a -licu -lkernel32 -lntdll -luserenv -lws2_32 -ldbghelp
import "C"
