// Code generated by lungo-dist; DO NOT EDIT.

package lungo

// Version is the lungo release of this module.
const Version = "1.78.3254"

// EnforceVersion1_78_3254 is referenced by the packages lungo 1.78.3254 generates, which
// build only with this module's version.
const EnforceVersion1_78_3254 = 0
