// Code generated by lungo-dist; DO NOT EDIT.

package lungo

// Version is the lungo release of this module.
const Version = "1.77.3244"

// EnforceVersion1_77_3244 is referenced by the packages lungo 1.77.3244 generates, which
// build only with this module's version.
const EnforceVersion1_77_3244 = 0
