// Code generated by lungo-dist; DO NOT EDIT.

package lungo

// Version is the lungo release of this module.
const Version = "1.88.0"

// EnforceVersion1_88_0 is referenced by the packages lungo 1.88.0 generates, which
// build only with this module's version.
const EnforceVersion1_88_0 = 0
